import { SupportedLocale } from './types';

export interface MedicalTermEntry {
  key: string;
  category: 'CARDIAC' | 'RESPIRATORY' | 'NEUROLOGY' | 'TRAUMA' | 'OBSTETRICS' | 'PHARMACOLOGY' | 'TRIAGE';
  en: string;
  translations: Record<SupportedLocale, string>;
  definitionEn: string;
}

export const VERIFIED_MEDICAL_GLOSSARY: MedicalTermEntry[] = [
  {
    key: 'CHEST_PAIN',
    category: 'CARDIAC',
    en: 'Acute Chest Pain / Angina',
    definitionEn: 'Acute ischemic or non-ischemic discomfort in anterior thorax with potential cardiac urgency.',
    translations: {
      en: 'Acute Chest Pain / Angina',
      as: 'বুকুৰ তীব্ৰ বিষ / এনজাইনা',
      bn: 'বুকে তীব্র ব্যথা / অ্যানজাইনা',
      brx: 'बिखायाव गोख्रों सानाय / एनजाइना',
      doi: 'छाती च तीखी पीड़ / एंजाइना',
      gu: 'છાતીમાં તીવ્ર દુખાવો / એન્જાઇના',
      hi: 'सीने में तीव्र दर्द / एनजाइना',
      kn: 'ತೀವ್ರ ಎದೆನೋವು / ಆಂಜಿನಾ',
      ks: 'سینَس مَنٛز سخت داگ / اینجائنا',
      kok: 'काळजात तीव्र दूख / एंजायना',
      mai: 'छाती मे तीव्र दर्द / एंजाइना',
      ml: 'കഠിനമായ നെഞ്ചുവേദന / ആൻജൈന',
      mni: 'থৱাক চিবগী অকনবা ৱাবা / এন্জাইনা',
      mr: 'छातीत तीव्र वेदना / एनजाइना',
      ne: 'छातीमा तीव्र दुखाइ / एन्जाइना',
      or: 'ଛାତିରେ ଗୁରୁତର ଯନ୍ତ୍ରଣା / ଏଞ୍ଜାଇନା',
      pa: 'ਛਾਤੀ ਵਿੱਚ ਤੇਜ਼ ਦਰਦ / ਐਨਜਾਈਨਾ',
      sa: 'तीव्रवक्षोवेदना / हृच्छूलम्',
      sat: 'ᱠᱚᱲᱟᱢ ᱨᱮ ᱟᱹᱰᱤ ᱡᱩᱨ ᱦᱟᱹᱥᱩ',
      sd: 'ڇاتيءَ ۾ سخت سور / اينجائنا',
      ta: 'கடுமையான நெஞ்சு வலி / ஆன்ஜைனா',
      te: 'తీవ్రమైన ఛాతీ నొప్పి / ఆంజినా',
      ur: 'سینے میں شدید درد / اینجائنا',
    },
  },
  {
    key: 'DYSPNEA',
    category: 'RESPIRATORY',
    en: 'Severe Dyspnea / Shortness of Breath',
    definitionEn: 'Sensation of severe air hunger or respiratory distress compromising oxygen exchange.',
    translations: {
      en: 'Severe Dyspnea / Shortness of Breath',
      as: 'উশাহ লোৱাত তীব্ৰ কষ্ট / শ্বাসকষ্ট',
      bn: 'তীব্র শ্বাসকষ্ট / ডিস্পনিয়া',
      brx: 'हाबिला लानो गोब्राब जानाय',
      doi: 'साह लैने दी भारी औखड़',
      gu: 'તીવ્ર શ્વાસ લેવામાં તકલીફ / ડિસ્પનિયા',
      hi: 'गंभीर सांस लेने में कठिनाई / डिस्पेनिया',
      kn: 'ತೀವ್ರ ಉಸಿರಾಟದ ತೊಂದರೆ / ಡಿಸ್ಪ್ನಿಯಾ',
      ks: 'دَم پھُٹُن / ساہ کڈھنس مَنٛز تکلیف',
      kok: 'श्वास घेवपाक व्हड त्रास / डिस्पेनिया',
      mai: 'सांस लै मे भारी कठिनाई / डिस्पेनिया',
      ml: 'കഠിനമായ ശ്വാസതടസ്സം / ഡിസ്പ്നിയ',
      mni: 'নুংশিৎ হোনবদা য়াম্না ৱাবা',
      mr: 'तीव्र श्वास लागणे / दम भरणे',
      ne: 'कडा सास फेर्न कठिनाइ / डिस्प्निया',
      or: 'ଗୁରୁତର ଶ୍ୱାସକଷ୍ଟ / ଦମ୍ ଫୁଲିବା',
      pa: 'ਗੰਭੀਰ ਸਾਹ ਘੁਟਣਾ / ਸਾਹ ਲੈਣ ਵਿੱਚ ਔਖ',
      sa: 'तीव्रश्वासकाठिन्यम् / श्वासकृच्छ्रम्',
      sat: 'ᱥᱟᱦᱮᱫ ᱦᱟᱛᱟᱣ ᱨᱮ ᱟᱹᱰᱤ ᱠᱚᱥᱴᱚ',
      sd: 'ساھ کڻڻ ۾ سخت ڏکيائي / ڊسپنيا',
      ta: 'கடுமையான மூச்சுத் திணறல் / டிஸ்ப்னியா',
      te: 'తీవ్రమైన శ్వాస ఆడకపోవడం / డిస్ప్నియా',
      ur: 'شدید سانس پھولنا / تنگیٔ تنفس',
    },
  },
  {
    key: 'LOSS_OF_CONSCIOUSNESS',
    category: 'NEUROLOGY',
    en: 'Loss of Consciousness / Syncope',
    definitionEn: 'Sudden temporary or prolonged lapse in responsiveness with neurovascular compromise.',
    translations: {
      en: 'Loss of Consciousness / Syncope',
      as: 'অজ্ঞান হোৱা / সংজ্ঞাহীনতা',
      bn: 'অজ্ঞান হয়ে যাওয়া / সংজ্ঞাহীনতা',
      brx: 'गोसो बानाय / बेहोश जानाय',
      doi: 'बेहोश होई जाना / अचेत',
      gu: 'બેભાન થઈ જવું / બેહોશી',
      hi: 'चेतना का ह्रास / बेहोशी',
      kn: 'ಪ್ರಜ್ಞೆ ಕಳೆದುಕೊಳ್ಳುವುದು / ಮೂರ್ಛೆ',
      ks: 'بے ہوش گژھُن / ہوش روۆن',
      kok: 'बेहोश जावप / भूल पडप',
      mai: 'बेहोश भ जायब / अचेत',
      ml: 'ബോധക്ഷയം / ബോധം നഷ്ടപ്പെടൽ',
      mni: 'ৱাখল তাইরোইবা / বেহোশ ওইবা',
      mr: 'शुद्ध हरपणे / बेशुद्धी',
      ne: 'चेतना गुमाउनु / बेहोस हुनु',
      or: 'ଚେତାଶୂନ୍ୟ ହେବା / ବେହୋସ୍',
      pa: 'ਬੇਹੋਸ਼ ਹੋ ਜਾਣਾ / ਗਸ਼ ਪੈਣਾ',
      sa: 'संज्ञानाशः / मूर्च्छा',
      sat: 'ᱵᱮᱦᱚᱸᱥ ᱦᱩᱭᱩᱜ / ᱦᱩᱥ ᱵᱟᱹᱱᱩᱜ',
      sd: 'بيھوش ٿيڻ / حواس وڃائڻ',
      ta: 'மயக்கமடைதல் / சுயநினைவு இழத்தல்',
      te: 'స్పృహ కోల్పోవడం / మూర్ఛ',
      ur: 'بے ہوشی / غشی کا دورہ',
    },
  },
  {
    key: 'HEMORRHAGE',
    category: 'TRAUMA',
    en: 'Severe Active Hemorrhage',
    definitionEn: 'Uncontrolled rapid blood loss endangering hemodynamics and perfusion.',
    translations: {
      en: 'Severe Active Hemorrhage',
      as: 'প্ৰচুৰ ৰক্তক্ষৰণ',
      bn: 'তীব্র রক্তক্ষরণ / হেমোরেজ',
      brx: 'गोख्रों थै बोहैनाय',
      doi: 'भारी खून वगना',
      gu: 'તીવ્ર રક્તસ્ત્રાવ / હેમરેજ',
      hi: 'गंभीर रक्तस्राव / खून बहना',
      kn: 'ತೀವ್ರ ರಕ್ತಸ್ರಾವ',
      ks: 'سخت خون دراون',
      kok: 'मोठ्या प्रमाणांत रगत व्हांवप',
      mai: 'भारी रक्तस्राव',
      ml: 'കഠിനമായ രക്തസ്രാവം',
      mni: 'ঈ য়াম্না চেন্দোকপা',
      mr: 'तीव्र रक्तस्राव / प्रचंड रक्त वाहणे',
      ne: 'कडा रक्तस्राव / धेरै रगत बग्नु',
      or: 'ପ୍ରବଳ ରକ୍ତସ୍ରାବ / ରକ୍ତ ବୋହିବା',
      pa: 'ਗੰਭੀਰ ਖੂਨ ਵਹਿਣਾ',
      sa: 'तीव्ररक्तस्रावः',
      sat: 'ᱟᱹᱰᱤ ᱡᱩᱨ ᱢᱟᱭᱟᱢ ᱡᱚᱨᱚ',
      sd: 'سخت رت وهيڻ',
      ta: 'கடுமையான ரத்தப்போக்கு',
      te: 'తీవ్రమైన రక్తస్రావం',
      ur: 'شدید خون بہنا / نزف الدم',
    },
  },
  {
    key: 'ALLERGY',
    category: 'PHARMACOLOGY',
    en: 'Drug Allergy / Anaphylaxis',
    definitionEn: 'Hypersensitivity reaction to pharmaceutical compounds or biological allergens.',
    translations: {
      en: 'Drug Allergy / Anaphylaxis',
      as: 'ঔষধৰ এলাৰ্জি / এনাফাইলেক্সিচ',
      bn: 'ওষুধের অ্যালার্জি / অ্যানাফিল্যাক্সিস',
      brx: 'मुलीनि एलार्जि / एनाफाइलेक्सिस',
      doi: 'दवाई दी एलर्जी',
      gu: 'દવાની એલર્જી / એનાફિલેક્સિસ',
      hi: 'दवा से एलर्जी / एनाफिलेक्सिस',
      kn: 'ಔಷಧಿ ಅಲರ್ಜಿ / ಅನಾಫಿಲ್ಯಾಕ್ಸಿಸ್',
      ks: 'دَواہٕچ الرجی / اینافیلیکسس',
      kok: 'वकतांची एलर्जी / एनाफायलॅक्सिस',
      mai: 'दवाइ सं एलर्जी',
      ml: 'മരുന്ന് അലർജി / അനാഫൈലാക്സിസ്',
      mni: 'হিদাক্কী এলার্জি',
      mr: 'औषधांची ॲलर्जी / ॲनाफायलॅक्सिस',
      ne: 'औषधीको एलर्जी / एनाफाइलेक्सिस',
      or: 'ଔଷଧ ଆଲର୍ଜି / ଆନାଫାଇଲାକ୍ସିସ୍',
      pa: 'ਦਵਾਈ ਦੀ ਐਲਰਜੀ',
      sa: 'औषधप्रत्यूर्जता / एनाफिलेक्सिस',
      sat: 'ᱨᱟᱱ ᱨᱮᱱᱟᱜ ᱮᱞᱟᱨᱡᱤ',
      sd: 'دوا جي الرجي / اينيفيليڪسس',
      ta: 'மருந்து ஒவ்வாமை / அனாபிலாக்சிஸ்',
      te: 'ఔషధ అలెర్జీ / అనాఫిలాక్సిస్',
      ur: 'دوائی کی الرجی / اینافیلیکسس',
    },
  },
  {
    key: 'AMBULANCE_DISPATCH',
    category: 'TRIAGE',
    en: 'Emergency Ambulance Assistance (108 / 112)',
    definitionEn: 'Priority mobile clinical emergency transport equipped with paramedic support.',
    translations: {
      en: 'Emergency Ambulance Assistance (108 / 112)',
      as: 'জৰুৰীকালীন এম্বুলেন্স সেৱা (১০৮ / ১১২)',
      bn: 'জরুরী অ্যাম্বুলেন্স সহায়তা (১০৮ / ১১২)',
      brx: 'गोख्रों एम्बुलेन्स हेफाजाब (১০৮ / ১১২)',
      doi: 'आपातकालीन एम्बुलेंस सहायता (१०८ / ११२)',
      gu: 'કટોકટી એમ્બ્યુલન્સ સહાય (૧૦૮ / ૧૧૨)',
      hi: 'आपातकालीन एम्बुलेंस सहायता (१०८ / ११२)',
      kn: 'ತುರ್ತು ಆಂಬ್ಯುಲೆನ್ಸ್ ನೆರವು (೧೦೮ / ೧೧೨)',
      ks: 'ہنگامی ایمبولینس مدد (۱۰۸ / ۱۱۲)',
      kok: 'तातडीची ॲम्ब्युलन्स सेवा (१०८ / ११२)',
      mai: 'आपातकालीन एम्बुलेंस सहायता (१०८ / ११२)',
      ml: 'അടിയന്തര ആംബുലൻസ് സഹായം (108 / 112)',
      mni: 'জরুরী এম্বুলেন্স মতেং (১০৮ / ১১২)',
      mr: 'तातडीची रुग्णवाहिका मदत (१०८ / ११२)',
      ne: 'आपतकालीन एम्बुलेन्स सहायता (१०८ / ११२)',
      or: 'ଜରୁରୀକାଳୀନ ଆମ୍ବୁଲାନ୍ସ ସହାୟତା (୧୦୮ / ୧୧୨)',
      pa: 'ਐਮਰਜੈਂਸੀ ਐਂਬੂਲੈਂਸ ਸਹਾਇਤਾ (੧੦੮ / ੧੧੨)',
      sa: 'आपत्कालीनरुग्णवाहनसहायता (१०८ / ११२)',
      sat: 'ᱟᱯᱟᱛᱠᱟᱞᱤᱱ ᱮᱢᱵᱩᱞᱮᱱᱥ ᱜᱚᱲᱚ (᱑᱐᱘ / ᱑᱑᱒)',
      sd: 'ھنگامي ايمبولينس مدد (۱۰۸ / ۱۱۲)',
      ta: 'அவசர ஆம்புலன்ஸ் உதவி (108 / 112)',
      te: 'అత్యవసర అంబులెన్స్ సహాయం (108 / 112)',
      ur: 'ہنگامی ایمبولینس امداد (۱۰۸ / ۱۱۲)',
    },
  },
];

export function getVerifiedTerm(key: string, locale: SupportedLocale): string {
  const entry = VERIFIED_MEDICAL_GLOSSARY.find(item => item.key === key);
  if (!entry) return key;
  return entry.translations[locale] || entry.en;
}
