import {
  PatientProfile,
  HealthcareWorkerProfile,
  TriageCase,
  Appointment,
  HealthDocument,
  NotificationItem,
  Referral,
  AuditLog,
  DocumentShare,
  PatientLocationData,
  AmbulanceRequest,
} from './types';

// =====================================================================
// DEMO USERS (Synthetic data only - strictly simulated)
// =====================================================================

export const DEMO_PATIENTS: PatientProfile[] = [
  {
    id: 'pat-001',
    role: 'PATIENT',
    syntheticId: 'PAT-2026-8912 [Synthetic]',
    maskedAadhaar: 'XXXX-XXXX-8912 [Synthetic Aadhaar]',
    fullName: 'Ramesh Nayak [Synthetic Patient]',
    phoneNumber: '+91 94370 12345 [Synthetic]',
    preferredLanguage: 'or',
    age: 48,
    gender: 'MALE',
    location: 'Athamallik, Angul District, Odisha [Synthetic Address]',
    emergencyContactName: 'Bikram Nayak (Son) [Synthetic]',
    emergencyContactPhone: '+91 94370 67890 [Synthetic]',
  },
  {
    id: 'pat-002',
    role: 'PATIENT',
    syntheticId: 'PAT-2026-3401 [Synthetic]',
    maskedAadhaar: 'XXXX-XXXX-3401 [Synthetic Aadhaar]',
    fullName: 'Sunita Sharma [Synthetic Patient]',
    phoneNumber: '+91 98610 23456 [Synthetic]',
    preferredLanguage: 'hi',
    age: 39,
    gender: 'FEMALE',
    location: 'Mangalabag, Cuttack, Odisha [Synthetic Address]',
    emergencyContactName: 'Manish Sharma (Husband) [Synthetic]',
    emergencyContactPhone: '+91 98610 78901 [Synthetic]',
  },
  {
    id: 'pat-003',
    role: 'PATIENT',
    syntheticId: 'PAT-2026-5573 [Synthetic]',
    maskedAadhaar: 'XXXX-XXXX-5573 [Synthetic Aadhaar]',
    fullName: 'Rajesh Patra [Synthetic Patient]',
    phoneNumber: '+91 97780 34567 [Synthetic]',
    preferredLanguage: 'en',
    age: 26,
    gender: 'MALE',
    location: 'Sector 4, Rourkela, Sundargarh, Odisha [Synthetic Address]',
    emergencyContactName: 'Kailash Patra (Father) [Synthetic]',
    emergencyContactPhone: '+91 97780 89012 [Synthetic]',
  },
];

export const DEMO_HEALTHCARE_WORKERS: HealthcareWorkerProfile[] = [
  {
    id: 'hcw-001',
    role: 'DOCTOR',
    fullName: 'Dr. Alok Mohanty [Synthetic Clinician]',
    phoneNumber: '+91 94371 99887 [Synthetic]',
    preferredLanguage: 'en',
    medicalCouncil: 'Odisha Medical Council (OMC)',
    registrationNumber: 'SMC-ODI-48291 [Synthetic Reg]',
    licenceNumber: 'MED-2015-9921 [Synthetic Licence]',
    facilityName: 'SCB Medical College & Hospital, Cuttack',
    department: 'Emergency & Acute Clinical Triage',
  },
  {
    id: 'hcw-002',
    role: 'NURSE',
    fullName: 'Sister Priyanka Senapati [Synthetic Nurse]',
    phoneNumber: '+91 98612 11223 [Synthetic]',
    preferredLanguage: 'or',
    medicalCouncil: 'Odisha Nursing Council',
    registrationNumber: 'SNC-ODI-19402 [Synthetic Reg]',
    licenceNumber: 'NUR-2018-4412 [Synthetic Licence]',
    facilityName: 'District Headquarters Hospital, Angul',
    department: 'Casualty & Outpatient Triage',
  },
];

// =====================================================================
// DEMO TRIAGE CASES (RED, YELLOW, GREEN, GREY with Multilingual Samples)
// =====================================================================

export const INITIAL_TRIAGE_CASES: TriageCase[] = [
  // 1. RED CASE (Odia patient - Acute Chest Pain / Hypoxia)
  {
    id: 'case-001',
    caseNumber: 'TB-2026-0101 [Synthetic Case]',
    patientId: 'pat-001',
    patientName: 'Ramesh Nayak [Synthetic Patient]',
    patientAge: 48,
    patientGender: 'MALE',
    patientLocation: 'Athamallik, Angul [Synthetic Location]',
    patientPhone: '+91 94370 12345 [Synthetic]',
    chiefComplaint: 'ପ୍ରବଳ ଛାତି ଯନ୍ତ୍ରଣା, ବାମ ହାତକୁ ଯନ୍ତ୍ରଣା ବ୍ୟାପିବା ଏବଂ ନିଶ୍ୱାସ ନେବାରେ କଷ୍ଟ [Synthetic Demo]',
    originalLanguage: 'or',
    detectedLanguage: 'or',
    translationConfidence: 97,
    originalStatement: 'ମୋର ଆଜି ସକାଳୁ ଛାତିରେ ପ୍ରବଳ ଯନ୍ତ୍ରଣା ହେଉଛି। ଯନ୍ତ୍ରଣା ବାମ ହାତ ଓ କାନ୍ଧ ଆଡ଼କୁ ବ୍ୟାପୁଛି। ନିଶ୍ୱାସ ନେବା ବହୁତ କଷ୍ଟକର ହେଉଛି ଓ ପ୍ରବଳ ଝାଳ ବୋହୁଛି।',
    translatedEnglishStatement: 'I have severe chest pain since this morning. The pain is radiating towards my left arm and shoulder. It is very hard to breathe and I am sweating profusely.',
    voiceTranscript: 'ଛାତି ଭାରୀ ଲାଗୁଛି ଆଜ୍ଞା... ଘଣ୍ଟାଏ ହେବ କିଛି କହିପାରୁନି... ବାମ ପାଖ ବହୁତ ବିନ୍ଧୁଛି... (Recorded at CHC Triage Kiosk)',
    audioUrl: '',
    structuredTriageNote: {
      chiefComplaint: 'Acute chest pain radiating to left arm with dyspnea and diaphoresis',
      symptoms: ['Severe chest tightness', 'Left arm and shoulder radiation', 'Dyspnea', 'Profuse sweating'],
      symptomDuration: 'Acute onset (< 4 hours)',
      severity: 'CRITICAL_ACUTE',
      severityTrajectory: 'CRITICAL_ACUTE',
      existingConditions: ['Hypertension (Stage 2)'],
      currentMedicines: ['Tab. Amlodipine 5mg OD'],
      allergies: ['No known drug allergies (NKDA)'],
      uploadedReportSummary: 'ECG Lead II/V3-V6 indicates acute anterolateral ST elevation',
      reportSummary: 'ECG Lead II/V3-V6 indicates acute anterolateral ST elevation',
      warningSigns: ['Acute Anginal Pain with arm radiation', 'Severe Hypoxia SpO2 88%'],
      missingInformation: ['Previous baseline 12-lead ECG', 'Serum Troponin-T levels'],
      suggestedUrgency: 'RED',
      patientLocation: 'Athamallik, Angul, Odisha',
      transportOrAmbulanceRequired: true,
      transportRequirement: 'EMERGENCY_AMBULANCE_DISPATCH',
      isDiagnostic: false,
      clinicalDisclaimer: 'AI-generated triage support — final decisions must be made by a qualified healthcare professional.',
      notesTimestamp: '2026-09-23T10:18:00Z',
    },
    status: 'SUBMITTED',
    provisionalUrgency: 'RED',
    facilityName: 'District Headquarters Hospital, Angul',
    department: 'Cardiology / Emergency Triage',
    vitals: {
      systolicBp: 178,
      diastolicBp: 104,
      heartRate: 118,
      oxygenSaturation: 88, // CRITICAL: < 90%
      temperatureCelsius: 37.1,
      respiratoryRate: 28,
      recordedAt: '2026-09-23T10:15:00Z',
    },
    uploadedReports: [
      {
        id: 'rep-001',
        fileName: 'Angul_DHH_ECG_Lead12.pdf',
        fileType: 'application/pdf',
        fileSizeBytes: 420500,
        storageUrl: '/demo/sample-ecg.pdf',
        category: 'IMAGING_SCAN',
        uploadedAt: '2026-09-23T10:18:00Z',
        extractedData: {
          id: 'ocr-ecg-001',
          reportId: 'rep-001',
          rawOcrText: '12-LEAD RESTING ECG: Sinus Tachycardia with ST elevation in Leads II, III, aVF (Inferior wall ischemia/infarction suspicion). QTc 460ms. Heart rate 118 bpm.',
          extractedLabValues: {
            'ECG Rhythm': 'Sinus Tachycardia',
            'ST Changes': 'ST elevation Leads II, III, aVF',
            'Ventricular Rate': '118 bpm',
          },
          suggestedDoctorName: 'Duty Medical Officer, Angul DHH',
          suggestedHospitalName: 'District Headquarters Hospital, Angul',
          ocrConfidence: 0.95,
          isConfirmedByPatient: true,
        },
      },
    ],
    redFlags: [
      {
        id: 'CHEST_PAIN',
        name: 'Acute Chest Pain / Cardiac Compromise',
        severity: 'CRITICAL',
        descriptionEn: 'Acute chest discomfort radiating to left arm with high ischemic risk.',
        descriptionHi: 'सीने में तीव्र दर्द जो बाएं हाथ तक फैल रहा है।',
        descriptionOr: 'ଛାତିରେ ପ୍ରବଳ ଯନ୍ତ୍ରଣା ବାମ ହାତକୁ ବ୍ୟାପୁଛି।',
        matchedTrigger: 'ଛାତି ଯନ୍ତ୍ରଣା / ବାମ ହାତ ବିନ୍ଧିବା',
      },
      {
        id: 'CRITICAL_HYPOXIA',
        name: 'Critical Hypoxia (SpO2 88%)',
        severity: 'CRITICAL',
        descriptionEn: 'Oxygen saturation dangerously low at 88%. Immediate supplemental oxygen required.',
        descriptionHi: 'ऑक्सीजन संतृप्ति 88% है जो खतरनाक रूप से कम है।',
        descriptionOr: 'ଅକ୍ସିଜେନ୍ ସ୍ତର 88% କୁ ଖସିଯାଇଛି, ତୁରନ୍ତ ଅକ୍ସିଜେନ୍ ଆବଶ୍ୟକ।',
        matchedTrigger: 'SpO2 88%',
      },
    ],
    followUpQuestions: [
      {
        id: 'fq-01',
        questionKey: 'DURATION',
        questionEn: 'How long has this severe chest tightness lasted?',
        questionHi: 'यह सीने का भारीपन कितने समय से है?',
        questionOr: 'ଏହି ଛାତି କଷ୍ଟ କେତେ ସମୟ ଧରି ଲାଗିରହିଛି?',
        reasonEn: 'Ischemic golden hour window determination.',
        answer: 'ପ୍ରାୟ ୨ ଘଣ୍ଟା ଧରି ଲଗାତାର ବଢ଼ିଚାଲିଛି (Continuous for about 2 hours)',
      },
    ],
    urgencyAssessment: {
      suggestedUrgency: 'RED',
      confidenceScore: 0.98,
      rationaleEn: 'Dual critical triggers: acute radiating chest pain combined with physiological hypoxia (SpO2 88%) and elevated systolic BP (178 mmHg). Immediate emergency physician evaluation mandated.',
      rationaleHi: 'दोहरे गंभीर संकेत: सीने में तेज दर्द, हाइपोक्सिया (SpO2 88%) और उच्च रक्तचाप। तत्काल आपातकालीन डॉक्टर समीक्षा आवश्यक है।',
      rationaleOr: 'ଦୁଇଟି ଗୁରୁତର ସତର୍କତା: ଛାତିରେ ଯନ୍ତ୍ରଣା ଓ ବିପଜ୍ଜନକ ଅକ୍ସିଜେନ୍ ସ୍ତର (୮୮%)। ତୁରନ୍ତ ଡାକ୍ତରଙ୍କ ସମୀକ୍ଷା ଆବଶ୍ୟକ।',
      triggeredRedFlags: ['Acute Anginal Pain', 'SpO2 < 90% (88%)', 'Hypertensive Urgency (SBP 178)'],
      missingInformation: ['Previous cardiac catheterization history'],
      isDiagnostic: false,
    },
    submittedAt: '2026-09-23T10:20:00Z',
    updatedAt: '2026-09-23T10:20:00Z',
  },

  // 2. YELLOW CASE (Hindi patient - High Remittent Fever with Leukocytosis)
  {
    id: 'case-002',
    caseNumber: 'TB-2026-0102 [Synthetic Case]',
    patientId: 'pat-002',
    patientName: 'Sunita Sharma [Synthetic Patient]',
    patientAge: 39,
    patientGender: 'FEMALE',
    patientLocation: 'Mangalabag, Cuttack [Synthetic Location]',
    patientPhone: '+91 98610 23456 [Synthetic]',
    chiefComplaint: '4 दिनों से तेज बुखार, ठंड लगना, पेट में गंभीर दर्द और उल्टी [Synthetic Demo]',
    originalLanguage: 'hi',
    detectedLanguage: 'hi',
    translationConfidence: 95,
    originalStatement: 'मुझे पिछले 4 दिनों से 102.5°F तक तेज बुखार आ रहा है। ठंड लगकर कंपकंपी होती है, पेट के दाहिने हिस्से में तेज दर्द है और कुछ भी खाने पर उल्टी हो जाती है।',
    translatedEnglishStatement: 'I have had high fever up to 102.5°F with severe chills and rigors for the last 4 days. Severe right quadrant abdominal pain and frequent vomiting after food.',
    voiceTranscript: 'चार दिन से बहुत तेज बुखार है डॉक्टर साहब, पेट में असहनीय दर्द है और कमजोरी से उठा नहीं जा रहा...',
    audioUrl: '',
    structuredTriageNote: {
      chiefComplaint: 'High remittent fever with rigors, abdominal pain, and intractable vomiting',
      symptoms: ['High grade fever (102.5°F)', 'Chills and rigors', 'Right quadrant abdominal pain', 'Vomiting after ingestion'],
      symptomDuration: '4 days progressive',
      severity: 'MODERATE_PROGRESSIVE',
      severityTrajectory: 'MODERATE_PROGRESSIVE',
      existingConditions: ['Type 2 Diabetes Mellitus (HbA1c 7.6%)'],
      currentMedicines: ['Tab. Metformin 500mg BD'],
      allergies: ['No known drug allergies (NKDA)'],
      uploadedReportSummary: 'CBC: Leukocytosis (WBC 15,200/uL), Widal TO 1:160, TH 1:320 Positive',
      reportSummary: 'CBC: Leukocytosis (WBC 15,200/uL), Widal TO 1:160, TH 1:320 Positive',
      warningSigns: ['High remittent fever > 39°C', 'Dehydration risk from vomiting'],
      missingInformation: ['Liver Function Test (LFT)', 'Blood culture sensitivity'],
      suggestedUrgency: 'YELLOW',
      patientLocation: 'Mangalabag, Cuttack, Odisha',
      transportOrAmbulanceRequired: false,
      transportRequirement: 'PRIORITY_OUTPATIENT_TRANSPORT',
      isDiagnostic: false,
      clinicalDisclaimer: 'AI-generated triage support — final decisions must be made by a qualified healthcare professional.',
      notesTimestamp: '2026-09-23T11:05:00Z',
    },
    status: 'AWAITING_REVIEW',
    provisionalUrgency: 'YELLOW',
    facilityName: 'SCB Medical College & Hospital, Cuttack',
    department: 'General Medicine / Fever Clinic',
    vitals: {
      systolicBp: 122,
      diastolicBp: 78,
      heartRate: 104,
      oxygenSaturation: 95,
      temperatureCelsius: 39.2, // HIGH FEVER
      respiratoryRate: 20,
      recordedAt: '2026-09-23T11:00:00Z',
    },
    uploadedReports: [
      {
        id: 'rep-002',
        fileName: 'Sunita_Sharma_CBC_Report.pdf',
        fileType: 'application/pdf',
        fileSizeBytes: 310000,
        storageUrl: '/demo/cbc-report.pdf',
        category: 'LABORATORY_REPORT',
        uploadedAt: '2026-09-23T11:05:00Z',
        extractedData: {
          id: 'ocr-cbc-002',
          reportId: 'rep-002',
          rawOcrText: 'CBC: WBC Total Count 15,200 /uL (ELEVATED), Neutrophils 84%, Platelets 2.10 Lakhs, Widal Test: S. Typhi TO 1:160, TH 1:320 (POSITIVE).',
          extractedLabValues: {
            'Total WBC': '15,200 /uL (HIGH)',
            'Neutrophils': '84%',
            'Widal TO': '1:160 Positive',
            'Widal TH': '1:320 Positive',
          },
          suggestedHospitalName: 'SCB Medical College & Hospital',
          suggestedDoctorName: 'Dr. Ananya Mishra',
          ocrConfidence: 0.96,
          isConfirmedByPatient: true,
        },
      },
    ],
    redFlags: [],
    followUpQuestions: [
      {
        id: 'fq-02',
        questionKey: 'PROGRESSION',
        questionEn: 'Are you able to keep oral liquids down without vomiting?',
        questionHi: 'क्या आप बिना उल्टी के पानी या ओआरएस पी पा रही हैं?',
        questionOr: 'ଆପଣ ବିନା ବାନ୍ତିରେ ପାଣି ବା ଓଆରଏସ୍ ପିଇପାରୁଛନ୍ତି କି?',
        reasonEn: 'Assesses dehydration and need for IV rehydration.',
        answer: 'बहुत मुश्किल है, बार-बार उल्टी हो रही है (Severe nausea and vomiting)',
      },
    ],
    urgencyAssessment: {
      suggestedUrgency: 'YELLOW',
      confidenceScore: 0.89,
      rationaleEn: 'High pyrexia (39.2°C) with significant leukocytosis (15,200 WBC) and positive enteric markers with persistent vomiting. Requires priority clinical evaluation and parenteral hydration/antibiotics.',
      rationaleHi: 'तेज बुखार (39.2°C), उच्च ल्यूकोसाइट्स और निर्जलीकरण का खतरा। प्राथमिकता समीक्षा आवश्यक है।',
      rationaleOr: 'ଅଧିକ ଜ୍ୱର ଓ ଡିହାଇଡ୍ରେସନ୍ ର ଆଶଙ୍କା। ପ୍ରାଥମିକତା ସମୀକ୍ଷା ଆବଶ୍ୟକ।',
      triggeredRedFlags: [],
      missingInformation: ['Recent travel history or contaminated water exposure'],
      isDiagnostic: false,
    },
    submittedAt: '2026-09-23T11:10:00Z',
    updatedAt: '2026-09-23T11:10:00Z',
  },

  // 3. GREEN CASE (English patient - Mild Chronic Dermatitis)
  {
    id: 'case-003',
    caseNumber: 'TB-2026-0103 [Synthetic Case]',
    patientId: 'pat-003',
    patientName: 'Rajesh Patra [Synthetic Patient]',
    patientAge: 26,
    patientGender: 'MALE',
    patientLocation: 'Sector 4, Rourkela [Synthetic Location]',
    patientPhone: '+91 97780 34567 [Synthetic]',
    chiefComplaint: 'Mild itchy skin rash on both forearms for 2 weeks, no fever [Synthetic Demo]',
    originalLanguage: 'en',
    originalStatement: 'I noticed red patches and mild itching on both my forearms over the past two weeks after handling garden compost. No fever, no breathing difficulty, no swelling on face.',
    translatedEnglishStatement: 'I noticed red patches and mild itching on both my forearms over the past two weeks after handling garden compost. No fever, no breathing difficulty, no swelling on face.',
    voiceTranscript: 'Mild itchy rash on forearms, no systemic issues, just annoying itching at night...',
    status: 'REVIEWED',
    provisionalUrgency: 'GREEN',
    finalUrgency: 'GREEN',
    facilityName: 'Rourkela Government Hospital (RGH)',
    department: 'Dermatology OPD',
    vitals: {
      systolicBp: 118,
      diastolicBp: 74,
      heartRate: 72,
      oxygenSaturation: 99,
      temperatureCelsius: 36.8,
      respiratoryRate: 14,
      recordedAt: '2026-09-22T14:30:00Z',
    },
    uploadedReports: [],
    redFlags: [],
    followUpQuestions: [
      {
        id: 'fq-03',
        questionKey: 'ALLERGIES',
        questionEn: 'Do you have known contact dermatitis or atopic eczema history?',
        questionHi: 'क्या आपको पहले कभी एक्जिमा या त्वचा एलर्जी हुई है?',
        questionOr: 'ଆପଣଙ୍କର ପୂର୍ବରୁ କୌଣସି ଚର୍ମ ଆଲର୍ଜି ଥିଲା କି?',
        reasonEn: 'Distinguishes contact dermatitis from infectious exanthem.',
        answer: 'Yes, mild skin sensitivity to chemical fertilizers.',
      },
    ],
    urgencyAssessment: {
      suggestedUrgency: 'GREEN',
      confidenceScore: 0.94,
      rationaleEn: 'Non-emergency localized contact dermatitis presentation. Completely stable physiological parameters, no systemic spread, no anaphylactic features.',
      rationaleHi: 'स्थिर और गैर-आपातकालीन स्थानीयकृत त्वचा संबंधी लक्षण। नियमित ओपीडी परामर्श उपयुक्त है।',
      rationaleOr: 'ସାଧାରଣ ଚର୍ମ ସମସ୍ୟା, ସ୍ୱାସ୍ଥ୍ୟ ସ୍ଥିର ରହିଛି। ନିୟମିତ ଓପିଡି ପରାମର୍ଶ ଉପଯୁକ୍ତ।',
      triggeredRedFlags: [],
      missingInformation: [],
      isDiagnostic: false,
    },
    clinicalReview: {
      id: 'cr-003',
      caseId: 'case-003',
      reviewerId: 'hcw-001',
      reviewerName: 'Dr. Alok Mohanty',
      reviewerRole: 'Medical Officer',
      reviewerRegNumber: 'SMC-ODI-48291',
      finalUrgency: 'GREEN',
      isOverridden: false,
      clinicalTriageNotes: 'Reviewed patient images and history. Compatible with localized contact irritant dermatitis. Recommended routine Dermatology OPD slot token #18. Prescribed topical calamine and antihistamine for symptomatic relief.',
      actionTaken: 'Assigned Routine Dermatology OPD Token #18 for tomorrow 10:30 AM.',
      reviewedAt: '2026-09-22T16:00:00Z',
    },
    submittedAt: '2026-09-22T14:35:00Z',
    updatedAt: '2026-09-22T16:00:00Z',
  },

  // 4. NEEDS_CLINICIAN_REVIEW CASE (Sparse info - Insufficient information / Low confidence)
  {
    id: 'case-004',
    caseNumber: 'TB-2026-0104 [Synthetic Case]',
    patientId: 'pat-001',
    patientName: 'Ramesh Nayak [Synthetic Patient]',
    patientAge: 48,
    patientGender: 'MALE',
    patientLocation: 'Athamallik, Angul [Synthetic Location]',
    patientPhone: '+91 94370 12345 [Synthetic]',
    chiefComplaint: 'ଅସୁସ୍ଥ ଲାଗୁଛି (Feeling unwell / fatigue) [Synthetic Demo]',
    originalLanguage: 'or',
    originalStatement: 'ଦେହ ଟିକେ ଭଲ ଲାଗୁନି (Not feeling good).',
    translatedEnglishStatement: 'Not feeling well, general malaise.',
    voiceTranscript: 'କିଛି ଭଲ ଲାଗୁନି...',
    status: 'MORE_INFO_REQUIRED',
    provisionalUrgency: 'NEEDS_CLINICIAN_REVIEW',
    facilityName: 'District Headquarters Hospital, Angul',
    department: 'General Triage',
    uploadedReports: [],
    redFlags: [],
    followUpQuestions: [
      {
        id: 'fq-04',
        questionKey: 'SYMPTOM_SPECIFICATION',
        questionEn: 'Could you specify if you have fever, pain, dizziness, or stomach upset?',
        questionHi: 'क्या आप स्पष्ट कर सकते हैं कि बुखार, दर्द या चक्कर आ रहा है?',
        questionOr: 'ଆପଣ ଦୟାକରି କହିପାରିବେ କି ଜ୍ୱର, ବିନ୍ଧା କିମ୍ବା ମୁଣ୍ଡ ବୁଲାଉଛି କି?',
        reasonEn: 'Minimal input requires symptom localization before triage assignment.',
      },
    ],
    urgencyAssessment: {
      suggestedUrgency: 'NEEDS_CLINICIAN_REVIEW',
      confidenceScore: 0.35,
      rationaleEn: 'Provisional urgency deferred to qualified clinician review due to insufficient baseline information. Essential vital signs, symptom duration, and clinical parameters are unmeasured. Never assume a missing value is normal.',
      rationaleHi: 'अधूरी जानकारी के कारण स्वचालित वर्गीकरण को डॉक्टर की समीक्षा के लिए सुरक्षित रखा गया है। बुनियादी शारीरिक संकेत अनुपलब्ध हैं।',
      rationaleOr: 'ଅସମ୍ପୂର୍ଣ୍ଣ ତଥ୍ୟ କାରଣରୁ ସ୍ୱତଃ ବର୍ଗୀକରଣ ବଦଳରେ ଡାକ୍ତରୀ ସମୀକ୍ଷା ପାଇଁ ପଠାଗଲା। କୌଣସି ଅନୁପସ୍ଥିତ ମୂଲ୍ୟକୁ ସ୍ୱାଭାବିକ ଧରାଯାଇନାହିଁ।',
      triggeredRedFlags: [],
      missingInformation: ['Specific complaints', 'Symptom duration', 'All vital signs (BP, SpO2, HR, RR, Temp, Glucose)', 'Consciousness level'],
      isDiagnostic: false,
      clinicalDisclaimer: 'AI-generated triage support — the final urgency and care decision must be made by a qualified healthcare professional.',
    },
    submittedAt: '2026-09-23T08:00:00Z',
    updatedAt: '2026-09-23T08:00:00Z',
  },
];

// =====================================================================
// DEMO APPOINTMENTS
// =====================================================================

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'appt-001',
    patientId: 'pat-001',
    caseId: 'case-001',
    hospitalName: 'SCB Medical College & Hospital, Cuttack [Synthetic Facility]',
    department: 'Cardiology Super-Specialty Unit',
    doctorName: 'Dr. B. K. Patnaik, DM (Cardio) [Synthetic]',
    appointmentDate: '2026-10-05',
    appointmentTime: '10:30 AM',
    locationRoom: 'Cardio OPD Counter 4, 2nd Floor New Block',
    status: 'UPCOMING',
    notes: 'Urgent post-triage coronary evaluation requested by Angul DHH triage team [Synthetic Appointment].',
    appointmentLetterUrl: '/demo/referral-letter-001.pdf',
    createdAt: '2026-09-23T10:45:00Z',
  },
  {
    id: 'appt-002',
    patientId: 'pat-002',
    caseId: 'case-002',
    hospitalName: 'SCB Medical College & Hospital, Cuttack [Synthetic Facility]',
    department: 'Infectious Disease / Fever OPD',
    doctorName: 'Dr. Ananya Mishra, MD [Synthetic]',
    appointmentDate: '2026-09-24',
    appointmentTime: '11:15 AM',
    locationRoom: 'Fever Clinic Room 12',
    status: 'COMPLETED',
    notes: 'Review with repeated Widal and liver enzyme profile [Synthetic Appointment].',
    createdAt: '2026-09-23T11:30:00Z',
  },
  {
    id: 'appt-003',
    patientId: 'pat-003',
    caseId: 'case-003',
    hospitalName: 'Rourkela Government Hospital [Synthetic Facility]',
    department: 'Dermatology OPD',
    doctorName: 'Dr. C. R. Sahoo [Synthetic]',
    appointmentDate: '2026-09-24',
    appointmentTime: '10:00 AM',
    locationRoom: 'OPD Room 7',
    status: 'COMPLETED',
    notes: 'Contact dermatitis review [Synthetic Appointment].',
    createdAt: '2026-09-22T16:15:00Z',
  },
];

// =====================================================================
// DEMO HEALTH DOCUMENTS (Vault)
// =====================================================================

export const INITIAL_HEALTH_DOCUMENTS: HealthDocument[] = [
  {
    id: 'doc-001',
    ownerId: 'pat-001',
    title: 'Hospital Discharge Summary - Angul DHH',
    category: 'DISCHARGE_SUMMARY',
    hospitalName: 'District Headquarters Hospital, Angul',
    doctorName: 'Dr. P. K. Dash, MD',
    documentDate: '2026-08-14',
    uploadDate: '2026-09-20',
    description: 'Past medical admission for viral bronchitis and hypertension management.',
    fileName: 'Angul_DHH_Discharge_Summary_Aug2026.pdf',
    fileSizeBytes: 654000,
    mimeType: 'application/pdf',
    ocrExtractedMetadata: {
      'Patient Name': 'Ramesh Nayak',
      'Age/Gender': '48/M',
      'Diagnosis': 'Acute Bronchitis with Essential Hypertension',
      'Discharge Meds': 'Tab Amlodipine 5mg OD, Syp Ambroxol',
    },
    isVerifiedByPatient: true,
  },
  {
    id: 'doc-002',
    ownerId: 'pat-001',
    title: 'Lipid Profile & Blood Glucose Test',
    category: 'LABORATORY_REPORT',
    hospitalName: 'Central Pathology Lab, Angul',
    doctorName: 'Dr. S. K. Mahapatra',
    documentDate: '2026-08-10',
    uploadDate: '2026-09-20',
    description: 'Routine quarterly fasting blood sugar and cholesterol panel.',
    fileName: 'Lipid_Panel_RameshNayak.pdf',
    fileSizeBytes: 420000,
    mimeType: 'application/pdf',
    ocrExtractedMetadata: {
      'Fasting Blood Sugar': '112 mg/dL (Borderline)',
      'Total Cholesterol': '218 mg/dL',
      'Triglycerides': '182 mg/dL',
      'HDL': '42 mg/dL',
      'LDL': '140 mg/dL',
    },
    isVerifiedByPatient: true,
  },
  {
    id: 'doc-003',
    ownerId: 'pat-002',
    title: 'Chest Digital Radiography X-Ray',
    category: 'IMAGING_SCAN',
    hospitalName: 'SCB Medical College & Hospital',
    doctorName: 'Dr. Ananya Mishra',
    documentDate: '2026-09-18',
    uploadDate: '2026-09-21',
    description: 'Digital X-Ray PA View for recurrent dry cough.',
    fileName: 'SCB_Chest_XRay_SunitaSharma.png',
    fileSizeBytes: 890000,
    mimeType: 'image/png',
    ocrExtractedMetadata: {
      'Impression': 'Prominent bronchovascular markings, no pleural effusion',
      'Cardiac Silhouette': 'Normal',
    },
    isVerifiedByPatient: true,
  },
];

// =====================================================================
// DEMO DOCUMENT SHARES (Controlled & Time-Limited)
// =====================================================================

export const INITIAL_DOCUMENT_SHARES: DocumentShare[] = [
  {
    id: 'share-001',
    documentId: 'doc-001',
    documentTitle: 'Hospital Discharge Summary - Angul DHH',
    ownerId: 'pat-001',
    sharedWithWorkerId: 'hcw-001',
    sharedWithWorkerName: 'Dr. Alok Mohanty',
    sharedWithWorkerRole: 'Doctor (Medical Officer)',
    caseId: 'case-001',
    caseNumber: 'TB-2026-0101',
    grantedAt: '2026-09-23T10:25:00Z',
    expiresAt: '2026-09-30T10:25:00Z', // 7 days validity
    isRevoked: false,
  },
];

// =====================================================================
// DEMO REFERRALS
// =====================================================================

export const INITIAL_REFERRALS: Referral[] = [
  {
    id: 'ref-001',
    caseId: 'case-001',
    caseNumber: 'TB-2026-0101',
    patientId: 'pat-001',
    patientName: 'Ramesh Nayak',
    referringWorkerName: 'Sister Priyanka Senapati (Angul DHH)',
    targetFacility: 'SCB Medical College & Hospital, Cuttack',
    targetDepartment: 'Cardiology Intensive Care Unit (ICU)',
    referralReason: 'Acute coronary syndrome presentation with SpO2 88% and ST changes on 12-lead ECG. Immediate interventional catheterization review needed.',
    urgency: 'RED',
    status: 'ACTIVE',
    createdAt: '2026-09-23T10:30:00Z',
  },
];

// =====================================================================
// DEMO NOTIFICATIONS
// =====================================================================

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-001',
    userId: 'pat-001',
    caseId: 'case-001',
    type: 'CASE_SUBMITTED',
    titleEn: 'Triage Case TB-2026-0101 Submitted',
    titleHi: 'ट्राइएज मामला TB-2026-0101 जमा किया गया',
    titleOr: 'ଟ୍ରାଏଜ୍ କେସ୍ TB-2026-0101 ସଫଳତାର ସହ ଦାଖଲ ହୋଇଛି',
    bodyEn: 'Your case has been placed in the priority clinical queue. Red-flag symptoms have alerted the duty medical officer.',
    bodyHi: 'आपका मामला आपातकालीन कतार में रखा गया है। ऑन-ड्यूटी डॉक्टर को सूचित कर दिया गया है।',
    bodyOr: 'ଆପଣଙ୍କ କେସ୍ ପ୍ରାଥମିକତା ଡାକ୍ତରୀ ଧାଡ଼ିରେ ଯୋଡ଼ାଯାଇଛି। ଡ୍ୟୁଟି ଡାକ୍ତରଙ୍କୁ ସତର୍କ କରାଯାଇଛି।',
    isRead: false,
    createdAt: '2026-09-23T10:21:00Z',
  },
  {
    id: 'notif-002',
    userId: 'pat-001',
    caseId: 'case-001',
    type: 'REFERRAL_CREATED',
    titleEn: 'Referral Order Issued to SCB Medical College',
    titleHi: 'एससीबी मेडिकल कॉलेज के लिए रेफरल आदेश जारी',
    titleOr: 'SCB ମେଡିକାଲ୍ କଲେଜକୁ ରେଫରାଲ୍ ଅର୍ଡର୍ ଜାରି ହୋଇଛି',
    bodyEn: 'Sister Priyanka Senapati referred you to Cardiology ICU for specialized evaluation.',
    bodyHi: 'कार्डियोलॉजी आईसीयू में तत्काल मूल्यांकन के लिए आपका रेफरल बनाया गया है।',
    bodyOr: 'ହୃଦରୋଗ ଆଇସିୟୁ ରେ ବିଶେଷଜ୍ଞ ଚିକିତ୍ସା ପାଇଁ ଆପଣଙ୍କୁ ରେଫର୍ କରାଯାଇଛି।',
    isRead: false,
    createdAt: '2026-09-23T10:31:00Z',
  },
  {
    id: 'notif-003',
    userId: 'pat-003',
    caseId: 'case-003',
    type: 'CASE_REVIEWED',
    titleEn: 'Triage Case TB-2026-0103 Reviewed',
    titleHi: 'ट्राइएज मामला TB-2026-0103 समीक्षित हुआ',
    titleOr: 'ଟ୍ରାଏଜ୍ କେସ୍ TB-2026-0103 ଡାକ୍ତରୀ ସମୀକ୍ଷା ସରିଛି',
    bodyEn: 'Dr. Alok Mohanty reviewed your symptoms and confirmed Routine (Green) status with OPD token #18.',
    bodyHi: 'डॉ. आलोक मोहंती ने आपके लक्षणों की समीक्षा की और नियमित ओपीडी टोकन #18 जारी किया।',
    bodyOr: 'ଡାକ୍ତର ଆଲୋକ ମହାନ୍ତି ଆପଣଙ୍କ ଲକ୍ଷଣ ଯାଞ୍ଚ କରି ଓପିଡି ଟୋକନ୍ #୧୮ ପ୍ରଦାନ କରିଛନ୍ତି।',
    isRead: true,
    createdAt: '2026-09-22T16:05:00Z',
  },
];

// =====================================================================
// DEMO AUDIT LOGS (Immutable Clinical Trail)
// =====================================================================

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-001',
    actorId: 'pat-001',
    actorName: 'Ramesh Nayak',
    actorRole: 'PATIENT',
    actionType: 'USER_LOGIN',
    resourceType: 'AUTH_SESSION',
    resourceId: 'pat-001',
    details: { authMethod: 'SIMULATED_AADHAAR_OTP', maskedAadhaar: 'XXXX-XXXX-8912' },
    ipAddress: '103.24.112.55 (Angul, IN)',
    timestamp: '2026-09-23T10:10:00Z',
  },
  {
    id: 'audit-002',
    actorId: 'pat-001',
    actorName: 'Ramesh Nayak',
    actorRole: 'PATIENT',
    actionType: 'PATIENT_CONSENT',
    resourceType: 'CONSENT_RECORD',
    resourceId: 'consent-pat-001',
    details: { consentGiven: true, noticeAcknowledged: 'AI_ASSISTIVE_ONLY_HUMAN_REVIEW_MANDATORY' },
    ipAddress: '103.24.112.55',
    timestamp: '2026-09-23T10:12:00Z',
  },
  {
    id: 'audit-003',
    actorId: 'pat-001',
    actorName: 'Ramesh Nayak',
    actorRole: 'PATIENT',
    actionType: 'FILE_UPLOAD',
    resourceType: 'MEDICAL_REPORT',
    resourceId: 'rep-001',
    details: { fileName: 'Angul_DHH_ECG_Lead12.pdf', mimeType: 'application/pdf', sizeBytes: 420500 },
    ipAddress: '103.24.112.55',
    timestamp: '2026-09-23T10:18:00Z',
  },
  {
    id: 'audit-004',
    actorId: 'SYSTEM',
    actorName: 'TriageEngine v2.6',
    actionType: 'RED_FLAG_SCREENED',
    resourceType: 'TRIAGE_CASE',
    resourceId: 'case-001',
    details: {
      triggeredFlags: ['CHEST_PAIN', 'CRITICAL_HYPOXIA'],
      spo2: 88,
      severity: 'CRITICAL',
      provisionalUrgency: 'RED',
    },
    timestamp: '2026-09-23T10:19:30Z',
  },
  {
    id: 'audit-005',
    actorId: 'pat-001',
    actorName: 'Ramesh Nayak',
    actorRole: 'PATIENT',
    actionType: 'TRIAGE_SUBMISSION',
    resourceType: 'TRIAGE_CASE',
    resourceId: 'case-001',
    details: { caseNumber: 'TB-2026-0101', chiefComplaint: 'Severe chest pain and dyspnea', language: 'or' },
    ipAddress: '103.24.112.55',
    timestamp: '2026-09-23T10:20:00Z',
  },
  {
    id: 'audit-006',
    actorId: 'hcw-001',
    actorName: 'Dr. Alok Mohanty',
    actorRole: 'DOCTOR',
    actionType: 'FINAL_DECISION_RECORDED',
    resourceType: 'TRIAGE_CASE',
    resourceId: 'case-003',
    details: {
      caseNumber: 'TB-2026-0103',
      finalUrgency: 'GREEN',
      isOverridden: false,
      reviewerRegNumber: 'SMC-ODI-48291',
      actionTaken: 'Assigned Routine Dermatology OPD Token #18',
    },
    ipAddress: '192.168.1.104 (SCB Intranet)',
    timestamp: '2026-09-22T16:00:00Z',
  },
];

// =====================================================================
// INITIAL PATIENT LOCATIONS (Consent-Gated & Audited)
// =====================================================================

export const INITIAL_PATIENT_LOCATIONS: PatientLocationData[] = [
  {
    patientId: 'pat-001',
    latitude: 20.8248,
    longitude: 84.5886,
    accuracyMeters: 14,
    address: 'Ward No 4, Hospital Road, Athamallik, Angul District, Odisha [Synthetic Address]',
    landmark: 'Near Athamallik Sub-Divisional Hospital Main Gate [Synthetic GPS]',
    district: 'Angul',
    pincode: '759125',
    emergencyContactNumber: '+91 94370 67890 [Synthetic]',
    locationType: 'HOME',
    sharingStatus: 'SHARING_ACTIVE',
    lastUpdated: '2026-09-23T11:45:00Z',
    sharedWithWorkerIds: ['hcw-001'],
    requiresTransportAssistance: true,
    distanceKmFromHospital: 1.4,
    accessLogs: [
      {
        id: 'loc-acc-001',
        workerId: 'hcw-001',
        workerName: 'Dr. Alok Mohanty, MD [Synthetic]',
        workerRole: 'DOCTOR',
        facilityName: 'SCB Medical College & Hospital, Cuttack',
        accessedAt: '2026-09-23T12:05:00Z',
      },
    ],
  },
  {
    patientId: 'pat-002',
    latitude: 20.4632,
    longitude: 85.8828,
    accuracyMeters: 8,
    address: 'Plot 34, Medical Road, Mangalabag, Cuttack, Odisha [Synthetic Address]',
    landmark: 'Opposite Ranihat High School [Synthetic GPS]',
    district: 'Cuttack',
    pincode: '753007',
    emergencyContactNumber: '+91 98610 78901 [Synthetic]',
    locationType: 'HOME',
    sharingStatus: 'SHARING_ACTIVE',
    lastUpdated: '2026-09-23T09:30:00Z',
    sharedWithWorkerIds: ['hcw-001'],
    requiresTransportAssistance: false,
    distanceKmFromHospital: 0.8,
    accessLogs: [],
  },
  {
    patientId: 'pat-003',
    latitude: 22.2604,
    longitude: 84.8536,
    accuracyMeters: 25,
    address: 'Sector 4, Rourkela, Sundargarh, Odisha [Synthetic Address]',
    landmark: 'Near Sector 4 Post Office [Synthetic GPS]',
    district: 'Sundargarh',
    pincode: '769002',
    emergencyContactNumber: '+91 97780 89012 [Synthetic]',
    locationType: 'HOME',
    sharingStatus: 'PRIVATE',
    lastUpdated: '2026-09-22T14:15:00Z',
    sharedWithWorkerIds: [],
    requiresTransportAssistance: false,
    distanceKmFromHospital: 5.2,
    accessLogs: [],
  },
];

// =====================================================================
// INITIAL AMBULANCE REQUESTS (Simulated Prototype)
// =====================================================================

export const INITIAL_AMBULANCE_REQUESTS: AmbulanceRequest[] = [
  {
    id: 'AMB-2026-8912',
    caseId: 'case-001',
    caseNumber: 'TB-2026-0101',
    patientId: 'pat-001',
    patientName: 'Ramesh Nayak',
    phoneNumber: '+91 94370 12345',
    emergencyContact: '+91 94370 67890 (Bikram Nayak - Son)',
    pickupAddress: 'Ward No 4, Hospital Road, Athamallik, Angul District, Odisha - 759125',
    pickupCoordinates: { lat: 20.8248, lng: 84.5886 },
    hospitalName: 'Athamallik Sub-Divisional Hospital (SCB Tele-Triage Network)',
    primarySymptoms: 'Acute retrosternal chest pressure, radiation to left arm, SpO2 88%',
    urgencyLevel: 'RED',
    status: 'EN_ROUTE',
    etaMinutes: 8,
    vehicleDetails: 'ALS Ambulance #OD-19-B-1082',
    driverDetails: 'Santosh Kumar Behera (Ph: +91 94371 99882) • EMT: Sister Pratima Das',
    requestedAt: '2026-09-23T11:46:00Z',
    timeline: [
      {
        status: 'REQUEST_SUBMITTED',
        timestamp: '2026-09-23T11:46:00Z',
        note: 'Emergency transport assistance requested by patient.',
      },
      {
        status: 'AWAITING_CONFIRMATION',
        timestamp: '2026-09-23T11:47:15Z',
        note: 'Dispatched to Angul 108 Emergency Control Cell.',
      },
      {
        status: 'AMBULANCE_ASSIGNED',
        timestamp: '2026-09-23T11:49:00Z',
        note: 'ALS Unit #OD-19-B-1082 assigned from Athamallik Base.',
      },
      {
        status: 'EN_ROUTE',
        timestamp: '2026-09-23T11:52:30Z',
        note: 'Ambulance en route to patient pickup location. ETA 8 mins.',
      },
    ],
    initiatedBy: 'PATIENT',
  },
];
